// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { Raffle$Type } from "./Raffle";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["Raffle"]: Raffle$Type;
    ["contracts/Raffle.sol:Raffle"]: Raffle$Type;
  }

  interface ContractTypesMap {
    ["Raffle"]: GetContractReturnType<Raffle$Type["abi"]>;
    ["contracts/Raffle.sol:Raffle"]: GetContractReturnType<Raffle$Type["abi"]>;
  }
}
