// This file was autogenerated by hardhat-viem, do not edit it.
// prettier-ignore
// tslint:disable
// eslint-disable

import "hardhat/types/artifacts";
import type { GetContractReturnType } from "@nomicfoundation/hardhat-viem/types";

import { RaffleSystem$Type } from "./RaffleSystem";

declare module "hardhat/types/artifacts" {
  interface ArtifactsMap {
    ["RaffleSystem"]: RaffleSystem$Type;
    ["contracts/RaffleSystem.sol:RaffleSystem"]: RaffleSystem$Type;
  }

  interface ContractTypesMap {
    ["RaffleSystem"]: GetContractReturnType<RaffleSystem$Type["abi"]>;
    ["contracts/RaffleSystem.sol:RaffleSystem"]: GetContractReturnType<RaffleSystem$Type["abi"]>;
  }
}
